name: One-time Delete All Cloudflare Lists

on:
  workflow_dispatch:  # Run manually from Actions tab

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq (JSON parser)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Delete all Cloudflare DNS lists
        run: |
          bash list_delete.sh
        env:
          API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
